version: "3.8"

services:
    database:
        build: ./database
        container_name: DATABASE
        environment:
            - POSTGRES_DB=kaggle_data
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data

    backend:
        build: ./backend
        container_name: BACKEND
        ports:
            - "3000:3000"
        depends_on:
            - database
        environment:
            - DB_HOST=database
            - DB_PORT=5432
            - DB_NAME=kaggle_data
            - DB_USER=postgres
            - DB_PASSWORD=postgres

    frontend:
        build: ./frontend
        container_name: FRONTEND
        ports:
            - "4173:4173"
        depends_on:
            - backend
        environment:
            - VITE_API_HOST=localhost
            - VITE_API_PORT=3000

volumes:
    postgres_data:
