apiVersion: v1
kind: Pod
metadata:
    name: backend-pod
    labels:
        app: backend
spec:
    containers:
        - name: backend
          image: your-backend-image:latest
          imagePullPolicy: IfNotPresent
          ports:
              - containerPort: 8000
                name: http
          env:
              - name: DATABASE_URL
                value: "postgresql://postgres:password123@postgres-service:5432/addiction_db"
          livenessProbe:
              httpGet:
                  path: /health
                  port: 8000
              initialDelaySeconds: 30
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          readinessProbe:
              httpGet:
                  path: /ready
                  port: 8000
              initialDelaySeconds: 5
              timeoutSeconds: 5
              periodSeconds: 5
