apiVersion: v1
kind: Pod
metadata:
    name: frontend-pod
    labels:
        app: frontend
spec:
    containers:
        - name: frontend
          image: your-frontend-image:latest
          imagePullPolicy: IfNotPresent
          ports:
              - containerPort: 80
                name: http
          env:
              - name: BACKEND_URL
                value: "http://backend-service:8000"
          livenessProbe:
              httpGet:
                  path: /
                  port: 80
              initialDelaySeconds: 10
              timeoutSeconds: 5
              periodSeconds: 10
              failureThreshold: 3
          readinessProbe:
              httpGet:
                  path: /
                  port: 80
              initialDelaySeconds: 5
              timeoutSeconds: 5
              periodSeconds: 5
